name: Spell Check

jobs:
  spellcheck:
    name: Run cspell
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install cspell
        run: npm install -g cspell
        
      - name: Run spell check
        run: cspell "./src/content/**"
